# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Description of what the lane does"
  lane :mac_lane do |options|

  	msg = options[:cmsg]
    # add actions here: https://docs.fastlane.tools/actions

    git_add

    git_commit(path: ".", message: "#{msg}")

    push_to_git_remote 
  end
end
